

service: awsSESExp

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - ses:*
      Resource: '*'


functions:
  sendEmail:
    handler: src/sendEmail.handler
    events: 
      - http:
          path: send-email
          method: post
          cors: true
 

